language: minimal
sudo: required

services:
  - docker

env:
  global:
    - CONDA_ENV: myrel
  matrix:
    - OS=ubuntu16.04 PYVER=2.7
    - OS=ubuntu16.04 PYVER=3.6
    - OS=centos6     PYVER=2.7
    - OS=centos6     PYVER=3.6

script:
  - export IMAGE=slaclcls/travis:$OS-py$PYVER
  - |
    if [[ $OS == ubuntu16.04 ]]; then
      export CC=gcc-7
      export CXX=g++-7
    else
      export CC=gcc
      export CXX=g++
    fi
  - docker run -v $PWD:/build -e CONDA_ENV -e PYVER -e CC -e CXX -ti $IMAGE bash -l /build/run_travis.sh
