language: minimal
sudo: required

services:
  - docker

env:
  global:
    - CONDA_ENV: myrel
  matrix:
    - OS=ubunt16.04 PYVER=2.7
    - OS=ubunt16.04 PYVER=3.6
    - OS=centos6    PYVER=2.7
    - OS=centos6    PYVER=3.6

script:
  - export IMAGE=slaclcls/travis:$OS-py$PYVER
  - docker run -v $PWD:/build -ti $IMAGE env CONDA_ENV=$CONDA_ENV PYVER=$PYVER CC=gcc-7 CXX=g++-7 /build/run_travis.sh
