sudo: required

services:
  - docker

env:
  global:
    - IMAGE: slaclcls/travis:test
    - CONDA_ENV: myrel
  matrix:
    # - PYVER=2.7
    - PYVER=3.6

script:
  - docker run -v $PWD:/build -ti $IMAGE env CONDA_ENV=$CONDA_ENV PYVER=$PYVER CC=gcc-7 CXX=g++-7 /build/run_travis.sh
